export const State = {
    STATE_CREATED: 'STATE_CREATED',
    STATE_INITIATING: 'STATE_INITIATING',
    STATE_LOADED: 'STATE_LOADED',
    STATE_STARTING: 'STATE_STARTING',
    STATE_STARTED: 'STATE_STARTED',
    STATE_PLAYING: 'STATE_PLAYING',
    STATE_PAUSING: 'STATE_PAUSING',
    STATE_PAUSED: 'STATE_PAUSED',
    STATE_RESUMING: 'STATE_RESUMING',
    STATE_RESUMED: 'STATE_RESUMED',
    STATE_INTERACTION: 'STATE_INTERACTION',
    STATE_STOPPING: 'STATE_STOPPING',
    STATE_STOPPED: 'STATE_STOPPED',
    STATE_ERROR: 'STATE_ERROR',
    STATE_TERMINATED: 'STATE_TERMINATED'
};

export type StateType = keyof typeof State;
